language: java
notifications:
  hipchat:
    rooms:
      secure: DS8rSYf/rpYexNHarvjSw9ozReXhM+5vukqSexZ38DwEDbSkwFh/WtYQUkT0oOcplie5iYWeebSDJXblMU88VzkICRnLkoT33oHl6BgpEvEPKKmcQCXkm6w3v+aOtgMOjfKtVOzGLqhq8Bxf1FEaGYDP99uzGGXAr+ORxy/k3GDzSs5ixaDOcLoM9OWPyZJ8Xf4VnWsNiywVf0b3zRdq2iMVQN1XPC0mEZocBk4ZLBCDVIMG61QwBFsUlVqp2bI5faDfki04ztQrYdUaGz402R6qP+nmg+3I6VNvE7G7Ax0owwqMvkNIE0wR5fRiVAZIr3aSe3s6E2Lk+c+gOG3a0b3TUEoitHSzYthwUEkva/ua/Isaoxx89sDf8dqVMAdlGI8IPXoFx09jJr6ceugv0g80adrY6eaKqdd4eoKHUqfViwKUN3QyO8oBVKPmB39xM1KzuZG9Xjahx/wmveBv1VE12moJi/Z+lNcvTilWeLAZFg+XPDnl+CwfJO2Kr/1Agl6cL7mW0ivGpM5zGx5NXuYOLeAziaFDaJ+9fPIUaOwkx+0/MxXsh/MG2PxOLZUojR20q3QyEw5oOEYELAcVQRUqwW/u+FgsPYYYkfo72qypAnFsL/ibgTv672AfFMM8Fq4lA0SB8p9smGw1iqjncmZRQTT9i4WrW51+NKRFk1M=
deploy:
  provider: releases
  api_key:
    secure: m17mqeTgs+Qj3KG11y5WtOb/KcX27r/NbpFZi3VG0M/Nf+Clg+qV9enWWYF3voB0e2crKkE6zLWWIRfxeHCbMqAv3LGKoHEEyO9R8DllgsQvoatKQhbhj9MU6NMERJGvdMlvJQEHRmieB0M2j693WbQV3Bn2sBfIzKFCqZl6zmuu6SDcqjwEGOzNJezc1DcaJ/EGF5sfKSqkNehaEYopO0gM2anH1+HgE0zKIC0crq+WAEmpHnyTNT78vDAwWxQkvLne5OFm3ck3MZGqfipF2bw+SNX0cpd7hJny4NTIpZCCzYPUrXMGrNSJtcl4kmQuRPgfUdXgZ0Fb707ZUyP3NzEuhu3P16baGXDjroRU8eH796yxXBiDj/y5qKKlfqnhRLf4nZ8+q/qwgQB3W2o3xWuGTXnWkjvGy1mMcJz9w3r8D0bbxliZkdFlk6UD52qjd3eVokPecm/ngr8CfrREQ7OvVdFbstLRfPFqChLkpmj44Y0aWtOML5cs6nlkOpV3Ud9qAiYJwdDkIxstGOJiN+aAFhQAN7eGtQNAqrukjvx6zDzkuhNK9mA+ZE2zGYu4DYADEP6ZUFcByZLQlFsohGNkbkc5TH+R92+KAFM33hFXvnnXfakCwYPI20BXKAMsBZyW0OuH8poOQ9J19yBbmqZk2J2/FxEIrE3pgBK53oU=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-was-installer-plugin
